# Generated by Django 5.1.2 on 2024-11-07 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('ad_type', models.CharField(choices=[('header_ads', 'Header Ads'), ('vertical_side_ads', 'Vertical Side Ads'), ('footer_ads', 'Footer Ads'), ('interstitial_ads', 'Interstitial Ads'), ('video_ads', 'Video Ads')], max_length=50)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[(1, 'FREE'), (2, 'GOLD'), (3, 'DIAMOND')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'INDIVIDUAL'), (2, 'ORGANIZATION')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_user', to='users.organization'),
        ),
    ]
