# Generated by Django 5.1.2 on 2024-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.IntegerField(choices=[(1, 'FREE'), (2, 'GOLD'), (3, 'DIAMOND')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'INDIVIDUAL'), (2, 'ORGANIZATION')], default=1),
        ),
    ]
