# Generated by Django 5.1.2 on 2024-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'INDIVIDUAL'), (2, 'ORGANIZATION'), (3, 'ADMIN')], default=1),
        ),
    ]
