# Generated by Django 5.1.2 on 2024-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userfeedback_is_active_userfeedback_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
