# Generated by Django 5.1.2 on 2024-12-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userfeedback_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
