# Generated by Django 5.1.2 on 2024-12-02 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_headless_browser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeloghistory',
            name='major_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='codeloghistory',
            index=models.Index(fields=['user', 'major_code'], name='selenium_he_user_id_c0e43c_idx'),
        ),
    ]
